version: '3.9'

services:
  kong-setup:
    build:
      context: .
    image: "alpine:latest"
    profiles: ["setup"]
    networks:
      - kong-net
  kong-deck:
    image: "kong/deck"
    profiles: ["setup"]
    environment:
      DECK_KONG_ADDR: "http://kong:8001"
    networks:
      - kong-net
    volumes:
      - ./config:/opt/kong
