_format_version: "1.1"
consumers:
- keyauth_credentials:
  - key: gzE65kElrcb209tk8nAsnSaAVXzmy3rF
  username: konga
services:
- connect_timeout: 60000
  host: 127.0.0.1
  name: admin-api
  plugins:
  - config:
      anonymous: null
      hide_credentials: false
      key_in_body: false
      key_in_header: true
      key_in_query: true
      key_names:
      - apikey
      run_on_preflight: true
    enabled: true
    name: key-auth
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 8001
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: 8374046d-cc00-4f73-a324-a0d025fb323b
    path_handling: v0
    paths:
    - /admin
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
